#!/bin/bash

# The MIT License (MIT)
#
# Copyright (c) 2013, 2014 Mateor
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

source BUILD

if [[ "$1" == "--skip" ]]; then
     echo ""
     echo "    You have disabled the HotSwapper bootstrap check."
     echo "    You now must set up your own Android build environment before using HotSwapper"
     echo ""
     echo "    If you later decide you want to use bootstrap, you can run \"sudo ./bootstrap\" at any time"
     echo ""
     touch $HOT_SWAPPER_LOC/.iproc
     exit 0
fi

if [ "$(id -u)" != "0" ]; then
     echo ""
     echo "    Because we are installing packages, bootstrap must be run with sudo"
     echo ""
     echo "         Please invoke \"sudo ./bootstrap\" to continue"
     echo ""
     exit 1
fi

CHK_BIT=$(getconf LONG_BIT) 
case "$CHK_BIT" in
64)
     BIT=64
     ;;
*)
     echo "You need to have a 64 bit OS to build Android. You will need to find a way to get one."
     exit 1
     ;;
esac

if !( [ -n "$(command -v apt-get)" ] || [[ "$OSTYPE" == "linux-gnu" ]] ); then
     echo "HotSwapper is only configured to work with Linux systems that have apt-get"
     echo "Ubuntu is recommended by Android, that is what this program is tested on"
     exit 1
fi


# Initialize a build environment for Linux users
echo "...Initializing Environment..."
sleep 2

# Install packages
#sudo add-apt-repository "deb http://archive.canonical.com/ lucid partner"
#sudo apt-get update
#sudo apt-get install sun-java6-jdk

sudo apt-get install git gnupg flex bison gperf build-essential \
  zip curl libc6-dev libncurses5-dev:i386 x11proto-core-dev \
  libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-glx:i386 \
  libgl1-mesa-dev g++-multilib mingw32 tofrodos \
  python-markdown libxml2-utils xsltproc zlib1g-dev:i386
  
# sym link libGL for unknown reasons. Hide output if already done.
sudo ln -s /usr/lib/i386-linux-gnu/mesa/libGL.so.1 /usr/lib/i386-linux-gnu/libGL.so >> /dev/null 2>&1


# I don't think we have to mess with the owner name. Let me know if you have problems.
# Udev rules courtesy of https://github.com/M0Rf30/android-udev-rules Thanks @M0Rf30!
[ -f /etc/udev/rules.d/*android* ] || sudo cp "$HOT_SWAPPER_LOC"/lib/udev.rules  /etc/udev/rules.d/51-android.rules

# Install repo
mkdir -p ~/bin
mkdir -p ~/android/system

curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
chmod a+x ~/bin/repo

if !([ -d "~/bin" ] && [[ ":$PATH:" != *":~/bin:"* ]]); then
     echo '# HotSwapper added bin to path for Android Builds'  >> ~/.bashrc
     echo 'export PATH=${PATH}:~/bin' >> ~/.bashrc
fi


echo ""
echo "Your Build environment has been intialized."
echo ""
echo " Please be aware we do not set-up CCACHE"
echo "CCACHE can considerably speed up your build, but takes up to 100 gigs of disk space."
echo ""
echo "If you can spare the space, see the directions on the Android website."
echo ""
echo "HotSwapper is ready to be run as you like. Enjoy!"
echo ""
touch "$HOT_SWAPPER_LOC"/.iproc
exit 0
