#!/bin/bash

# The MIT License (MIT)
#
# Copyright (c) 2014 Mateor
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Switch between building any of several popular custom ROMs.


# PLEASE edit values in BUILD file or WOE BETIDE YOU!

# populate environmental variables and pass to children
source BUILD
set -a


usage () {
     echo ""
     echo "DESCRIPTION:"
     echo ""
     echo "Small shell app by @mateor."
     echo "    Easily switch between custom rom flavors and branches."
     echo ""
     echo "!! You will want to set some environmental variables in the BUILD file !!"
     echo ""
     echo "OPTIONS:"
     echo "    ${bold}make${normal} ( ${bold}<ROMTYPE>${normal} || ${bold}<ANDROID_VERSION>${normal} )" 
     echo "           : creates a flashable zip of one of several ROMTYPES"
     echo ""
     echo "             valid ${bold}ROMTYPES${normal} are ( aosp, cm, aokp, omni, pac, pa, vanir, slim)"
     echo "             valid ${bold}ANDROID_VERSION${normal} depends on ROMTYPE, it's the Android version:
                              (2.3, 4.0, 4.1. 4.2. 4.3. 4.4 )"
     echo "             This command should pull sources, lunch, and build binaries"
     echo ""
     exit $exit_code
}

remind_about_BUILD() {
     echo ""
     echo " You must edit the files in ${HOT_SWAPPER_LOC}/BUILD"
     echo ""
     echo " This is a safety precaution to keep users from downloading in accidental places."
     echo " Please create a directory to correspond with the ANDROID_HOME entry in BUILD file."
     echo ""
     exit 1
}

prompt_bootstrap() {
     echo ""
     echo "    It looks like this is the first time you have run the HotSwapper."
     echo ""
     echo "    In order to begin building Android ROMs, you must initialize the build environment."
     echo ""
     echo "    \"sudo ./bootstrap\" will install the packages you need to build."
     echo "    Bootstrapping requires sudo, because it installs packages."
     echo ""
     echo "    Skip this and set up your own by running \"./bootstrap --skip\""
     echo ""
     exit 1
}

if [[ "$#" == 0 ]]; then
     usage
fi

# check for lifelines
for arg in $@; do
     #TODO @mateor Add a help for each command
     if ( [[ $arg == "h" ]] || [[ $arg == "-h" ]] || [[ $arg == "--h" ]] || [[ $arg == "help" ]] || [[ $arg == "-help" ]] || [[ $arg == "--help" ]] ); then
          usage
     fi
done

# Explicitly check for ANDROID_HOME to avoid people downloading source in the wrong spot by accident.
[[ -d $ANDROID_HOME ]] || remind_about_BUILD

# check if they have bootstrapped. If not do so. This should be non-destructive to existing build enviroments.
[[ -f "$HOT_SWAPPER_LOC"/.iproc ]] || prompt_bootstrap

case "$1" in
[Mm]ake)
     # I would at one point like to manage the exit code to make these conditional
     #    but it will require some investigation into the standard return values from make.
     source $HOT_SWAPPER_LOC/src/orderBuilds.sh "$2" "$3"
     ;;
[Pp]ull)
     # just fetch sources and don't compile
     # how best to do this?
     ;;
*)
     echo ""
     echo "!!! Command not recognized !!!"
     exit_code=-1 && usage
     ;;
esac

exit 0
